### ISSUE TITLE
Feature Request - SAS lock

### ISSUE THREAD

**Issue by Tabris83** [Xyphos/KSP_SASAG#1]
when in physics range (2.3km) toggle SAS-Hold.

useful for docking.

**Comment by Xyphos** [comment]
That's what SAS is for?
https://github.com/Xyphos/KSP_SASAG/blob/master/SASAG.cs#L32

**Comment by Tabris83** [comment]
Hyper edit 2 craft into orbit, set SAS to prograde on one.
Switch to the other craft, set SAS.
switch back to the original craft, SAS will be set to Stability assist and it will be off Prograde.

**Comment by Xyphos** [comment]
That's KSP itself, not my code, I can't fix that issue because it's not related to this mod.
all I can tell you, is to keep pressing whatever AG you're using to reset the SAS mode.

but, I don't recommend using prograde-hold for docking; instead try target-hold and translate your prograde marker to be centered with the target; works every time with no adjusting of the second vessel.
